# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nb_vue',
            field=models.IntegerField(default=0, verbose_name=b'Nombre de Vue'),
            preserve_default=False,
        ),
    ]
