# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_personne'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='nb_modif',
            field=models.IntegerField(default=0, verbose_name=b'Nombre de Modification'),
            preserve_default=False,
        ),
    ]
