# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-19 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170307_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='nb_modif',
            field=models.IntegerField(default=0, null=True, verbose_name=b'Nombre de Modification'),
        ),
    ]
